### ISSUE TITLE
It's Crashing

### ISSUE THREAD

**Issue by phantomabid** [RacoonDog/Electron#2]
```
[09:25:13] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.12
[09:25:14] [main/INFO]: Loading 110 mods:
	- bananaplus 100
	- baritone-meteor 1.19.3-SNAPSHOT via meteor-client
	- betterf3 5.0.0
	- caffeineconfig 1.0.0+1.17 via sodium-extra
	- carpet 1.4.93
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 9.0.94
	- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
	- com_moandjiezana_toml_toml4j 0.7.2 via ukulib
	- electron 0.3.6
	- entityculling 1.5.2-mc1.19.3
	- fabric-api 0.69.1+1.19.3
	- fabric-api-base 0.4.19+8d1895cf85 via fabric-api
	- fabric-api-lookup-api-v1 1.6.18+49abcf7e85 via fabric-api
	- fabric-biome-api-v1 12.0.0+689f5e7185 via fabric-api
	- fabric-block-api-v1 1.0.3+12bfe4ea85 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.28+c6af733c85 via fabric-api
	- fabric-client-tags-api-v1 1.0.9+49abcf7e85 via fabric-api
	- fabric-command-api-v1 1.2.19+f71b366f85 via fabric-api
	- fabric-command-api-v2 2.1.16+99f9db8085 via ukulib
	- fabric-commands-v0 0.2.36+df3654b385 via fabric-api
	- fabric-containers-v0 0.1.44+df3654b385 via fabric-api
	- fabric-content-registries-v0 3.4.12+49abcf7e85 via fabric-api
	- fabric-convention-tags-v1 1.2.0+8e4e694f85 via fabric-api
	- fabric-crash-report-info-v1 0.2.12+aeb40ebe85 via fabric-api
	- fabric-data-generation-api-v1 11.1.1+112a38be85 via fabric-api
	- fabric-dimensions-v1 2.1.39+48349a3f85 via fabric-api
	- fabric-entity-events-v1 1.5.5+b83334a085 via fabric-api
	- fabric-events-interaction-v0 0.4.37+422b77fb85 via fabric-api
	- fabric-events-lifecycle-v0 0.2.39+df3654b385 via fabric-api
	- fabric-game-rule-api-v1 1.0.28+2894d6df85 via fabric-api
	- fabric-item-api-v1 2.1.5+4d2c606385 via fabric-api
	- fabric-item-group-api-v1 2.1.8+d3d735d085 via fabric-api
	- fabric-key-binding-api-v1 1.0.28+aaaf9d3385 via fabric-api
	- fabric-keybindings-v0 0.2.26+df3654b385 via fabric-api
	- fabric-language-kotlin 1.9.0+kotlin.1.8.0
	- fabric-lifecycle-events-v1 2.2.8+2894d6df85 via fabric-api
	- fabric-loot-api-v2 1.1.18+75e9821185 via fabric-api
	- fabric-loot-tables-v1 1.1.22+9e7660c685 via fabric-api
	- fabric-message-api-v1 5.0.12+6ede1da985 via fabric-api
	- fabric-mining-level-api-v1 2.1.29+49abcf7e85 via fabric-api
	- fabric-models-v0 0.3.25+11ba9c3b85 via fabric-api
	- fabric-networking-api-v1 1.2.14+d9ac3c3985 via fabric-api
	- fabric-networking-v0 0.3.31+df3654b385 via fabric-api
	- fabric-object-builder-api-v1 5.2.0+e9dee00485 via fabric-api
	- fabric-particles-v1 1.0.18+fbde993d85 via fabric-api
	- fabric-registry-sync-v0 2.0.1+2608564685 via fabric-api
	- fabric-renderer-api-v1 2.1.0+2063beff85 via fabric-api
	- fabric-renderer-indigo 0.6.23+11ba9c3b85 via fabric-api
	- fabric-renderer-registries-v1 3.2.28+df3654b385 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.23+48349a3f85 via fabric-api
	- fabric-rendering-fluids-v1 3.0.16+3067f46385 via fabric-api
	- fabric-rendering-v0 1.1.31+df3654b385 via fabric-api
	- fabric-rendering-v1 1.11.7+49abcf7e85 via fabric-api
	- fabric-resource-conditions-api-v1 2.2.0+280be3ab85 via fabric-api
	- fabric-resource-loader-v0 0.10.4+a91e48b785 via ukulib
	- fabric-screen-api-v1 1.0.39+1d4d0b5785 via fabric-api
	- fabric-screen-handler-api-v1 1.3.10+689f5e7185 via fabric-api
	- fabric-sound-api-v1 1.0.6+75e9821185 via fabric-api
	- fabric-transfer-api-v1 2.1.12+82a2701785 via fabric-api
	- fabric-transitive-access-wideners-v1 2.1.0+0efcd39b85 via fabric-api
	- fabricloader 0.14.12
	- gs_mclo_java_mclogs-java 2.1.1 via ukulib
	- hig-tools 2.1
	- indium 1.0.12+mc1.19.3
	- io_github_douira_glsl-transformer 2.0.0-pre8 via iris
	- iris 1.5.1
	- itemscroller 0.18.0
	- java 17
	- jei 12.1.1.9
	- lazydfu 0.1.3
	- litematica 0.13.1
	- lithium 0.10.4
	- malilib 0.14.0
	- meteor-client 0.5.2-1756
	- meteor-crash-addon 0.6
	- meteor-rejects 0.2
	- meteor-shared-addon-utils 1.2.9 via electron
	- meteor-villager-roller 1.3.5+mc1.19.3-build.41
	- meteorplus 1.1
	- minecraft 1.19.3
	- minihud 0.25.0
	- modmenu 5.0.2
	- multiconnect 1.6-beta.25
	- numbyhack 1.9
	- org_anarres_jcpp 1.4.14 via iris
	- org_antlr_antlr4-runtime 4.11.1 via iris
	- org_jetbrains_kotlin_kotlin-reflect 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.5 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
	- orion 0.1
	- reaper 0.1
	- reeses-sodium-options 1.4.9+mc1.19.2-build.67
	- seedcrackerx-api 2.10.1 via meteor-rejects
	- sodium 0.4.8+build.22
	- sodium-extra 0.4.16+mc1.19.3-build.91
	- starlight 1.1.1+fabric.ae22326
	- streak-addon 0.2.9-1.19.2
	- tanuki 0.1
	- tweakeroo 0.15.0
	- ukulib 0.6.1+1.19.3
	- wi_zoom 1.4-MC1.19.3
[09:25:14] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/beast/AppData/Roaming/easymc-launcher/minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[09:25:14] [main/INFO]: Compatibility level set to JAVA_16
[09:25:14] [main/INFO]: Compatibility level set to JAVA_17
[09:25:14] [main/INFO]: Loaded configuration file for Lithium: 106 options available, 1 override(s) found
[09:25:14] [main/WARN]: Reference map 'meteor-crash-addon-refmap.json' for meteorcrashaddon.mixins.json could not be read. If this is a development environment you can ignore this message
[09:25:14] [main/INFO]: Loaded configuration file for Sodium: 33 options available, 1 override(s) found
[09:25:15] [main/INFO]: Loaded configuration file for Sodium Extra: 28 options available, 0 override(s) found
[09:25:15] [main/WARN]: Force-disabling mixin 'entity.data_tracker.no_locks.DataTrackerMixin' as rule 'mixin.entity.data_tracker' (added by mods [multiconnect]) disables it and children
[09:25:15] [main/WARN]: Force-disabling mixin 'entity.data_tracker.use_arrays.DataTrackerMixin' as rule 'mixin.entity.data_tracker' (added by mods [multiconnect]) disables it and children
[09:25:15] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[09:25:19] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity from mod tweakeroo->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockEntity_limitsMixin from mod carpet->@ModifyConstant::negativeLimit(I)I with priority 1000
[09:25:19] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity from mod tweakeroo->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockEntity_limitsMixin from mod carpet->@ModifyConstant::positiveLimit(I)I with priority 1000
[09:25:19] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity from mod tweakeroo->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockEntity_limitsMixin from mod carpet->@ModifyConstant::negativeLimit(I)I with priority 1000
[09:25:19] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity from mod tweakeroo->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockEntity_limitsMixin from mod carpet->@ModifyConstant::positiveLimit(I)I with priority 1000
[09:25:19] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity from mod tweakeroo->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockEntity_limitsMixin from mod carpet->@ModifyConstant::negativeLimit(I)I with priority 1000
[09:25:19] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity from mod tweakeroo->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockEntity_limitsMixin from mod carpet->@ModifyConstant::positiveLimit(I)I with priority 1000
[09:25:19] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity from mod tweakeroo->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockEntity_limitsMixin from mod carpet->@ModifyConstant::positiveLimit(I)I with priority 1000
[09:25:19] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity from mod tweakeroo->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockEntity_limitsMixin from mod carpet->@ModifyConstant::positiveLimit(I)I with priority 1000
[09:25:19] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity from mod tweakeroo->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockEntity_limitsMixin from mod carpet->@ModifyConstant::positiveLimit(I)I with priority 1000
[09:25:20] [main/INFO]: Building unoptimized datafixer
[09:25:22] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder from mod sodium, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[09:25:22] [Render thread/INFO]: Launching a new process to probe the system configuration!
[09:25:23] [Render thread/INFO]: OpenGL Vendor: NVIDIA Corporation
[09:25:23] [Render thread/INFO]: OpenGL Renderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
[09:25:23] [Render thread/INFO]: OpenGL Version: 3.3.0 NVIDIA 528.24
[09:25:23] [Render thread/WARN]: Enabling workaround for NVIDIA graphics drivers on Windows (issue #1486)
[09:25:23] [Render thread/WARN]: One or more workarounds were enabled to prevent crashes or other issues on your system. You may need to update your graphics drivers.
[09:25:23] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[09:25:25] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:156) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:161) ~[authlib-3.16.29.jar:?]
	at net.minecraft.class_310.method_31382(class_310.java:724) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:437) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:205) ~[1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:87) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-3.16.29.jar:?]
	... 9 more
[09:25:25] [Render thread/INFO]: Setting user: martusin
[09:25:25] [Render thread/WARN]: @Redirect conflict. Skipping mixins.tweakeroo.json:MixinServerPlayNetworkHandler from mod tweakeroo->@Redirect::tweakeroo_removeHitPosCheck(Lnet/minecraft/class_243;Lnet/minecraft/class_243;)Lnet/minecraft/class_243; with priority 1005, already redirected by mixins.litematica.json:MixinServerPlayNetworkHandler from mod litematica->@Redirect::litematica_removeHitPosCheck(Lnet/minecraft/class_243;Lnet/minecraft/class_243;)Lnet/minecraft/class_243; with priority 1010
[09:25:25] [ForkJoinPool.commonPool-worker-1/INFO]: Found via translator: .\config\multiconnect\via-translator-1.6-beta.25.jar
[09:25:25] [ForkJoinPool.commonPool-worker-2/INFO]: Downloaded ViaVersion
[09:25:25] [Render thread/INFO]: Using multiconnect translator: net.earthcomputer.multiconnect.impl.via.ViaMulticonnectTranslator
[09:25:26] [Via-Mappingloader-0/INFO]: Loading 1.12 -> 1.13 mappings...
[09:25:26] [Via-Mappingloader-1/INFO]: Loading 1.13 -> 1.13.2 mappings...
[09:25:26] [multiconnect sync executor/WARN]: You are running a development version of the plugin, please report any bugs to GitHub.
[09:25:26] [Via-Mappingloader-2/INFO]: Loading 1.13.2 -> 1.14 mappings...
[09:25:26] [Via-Mappingloader-3/INFO]: Loading 1.14 -> 1.15 mappings...
[09:25:26] [Via-Mappingloader-0/INFO]: Loading block connection mappings ...
[09:25:26] [Via-Mappingloader-4/INFO]: Loading 1.15 -> 1.16 mappings...
[09:25:26] [Via-Mappingloader-3/INFO]: Loading 1.16 -> 1.16.2 mappings...
[09:25:26] [Via-Mappingloader-3/INFO]: Loading 1.16.2 -> 1.17 mappings...
[09:25:26] [Via-Mappingloader-0/INFO]: Loading 1.17 -> 1.18 mappings...
[09:25:26] [Via-Mappingloader-0/INFO]: Loading 1.18 -> 1.19 mappings...
[09:25:26] [Via-Mappingloader-0/INFO]: Loading 1.19 -> 1.19.3 mappings...
[09:25:26] [Render thread/INFO]: ViaVersion version: 4.5.2-SNAPSHOT
[09:25:26] [Render thread/INFO]: [STDOUT]: Starting WI Zoom v1.4-MC1.19.3
[09:25:26] [Render thread/INFO]: [BetterF3] Loading...
[09:25:26] [Render thread/INFO]: [BetterF3] All done!
[09:25:27] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[09:25:27] [multiconnect sync executor/INFO]: Finished mapping loading, shutting down loader executor!
[09:25:27] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[09:25:27] [Render thread/ERROR]: Mod multiconnect provides a broken implementation of ModMenuApi
net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'modmenu' provided by 'multiconnect'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56) ~[fabric-loader-0.14.12.jar:?]
	at com.terraformersmc.modmenu.ModMenu.lambda$onInitializeClient$0(ModMenu.java:74) ~[modmenu-5.0.2.jar:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at com.terraformersmc.modmenu.ModMenu.onInitializeClient(ModMenu.java:70) ~[modmenu-5.0.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) ~[fabric-loader-0.14.12.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:465) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:205) ~[1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]
Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: net.earthcomputer.multiconnect.impl.ModMenuImpl
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:52) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.12.jar:?]
	... 12 more
Caused by: java.lang.ClassNotFoundException: net.earthcomputer.multiconnect.impl.ModMenuImpl
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.12.jar:?]
	... 12 more
[09:25:27] [ForkJoinPool.commonPool-worker-2/WARN]: [Iris Update Check] Cached update file detected, using that!
[09:25:27] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[09:25:28] [Render thread/INFO]: ARB_direct_state_access detected, enabling DSA.
[09:25:28] [Render thread/INFO]: Debug functionality is disabled.
[09:25:28] [Render thread/INFO]: Profile: Custom (+14 options changed by user)
[09:25:29] [Render thread/INFO]: Using shaderpack: ComplementaryShaders_v4.7.zip
[09:25:29] [Render thread/WARN]: Missing metadata in pack file/midnight-s-swords-texture-pack-v0-03.zip
[09:25:29] [Render thread/WARN]: Method overwrite conflict for getMeteorSplashes in streak.mixins.json:SplashTextResourceSupplierMixin from mod streak-addon, previously written by meteordevelopment.meteorclient.mixin.SplashTextResourceSupplierMixin. Skipping method.
[09:25:29] [Render thread/INFO]: Hardware information:
[09:25:29] [Render thread/INFO]: CPU: 12x AMD Ryzen 5 5600X 6-Core Processor 
[09:25:29] [Render thread/INFO]: GPU: NVIDIA GeForce RTX 3060/PCIe/SSE2 (Supports OpenGL 3.2.0 NVIDIA 528.24)
[09:25:29] [Render thread/INFO]: OS: Windows 10 (10.0)
[09:25:30] [Render thread/INFO]: Narrator library for x64 successfully loaded
[09:25:30] [Render thread/INFO]: Reloading ResourceManager: vanilla, Fabric Mods (BetterF3, CaffeineConfig, Carpet Mod, Cloth Config v9, Electron, EntityCulling-Fabric, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Client Tags, Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Group API (v1), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Language Kotlin, Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Sound API (v1), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, HIG Tools, Indium, Iris, Item Scroller, Just Enough Items, LazyDFU, Litematica, Lithium, MaLiLib, Meteor Client, Meteor Crash Addon, Meteor Rejects, Meteor Shared Addon Utils, Meteor Villager Roller, MeteorPlus, MiniHUD, Mod Menu, MultiConnect, Numby Hack, Orion, Reaper, Reese's Sodium Options, SeedCrackerX API, Sodium, Sodium Extra, Starlight, TrouserStreak, Tanuki, Tweakeroo, ukulib, WI Zoom)
[09:25:30] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[09:25:30] [Render thread/INFO]: Starting custom uniform resolving
[09:25:30] [Render thread/WARN]: Failed to resolve uniform rainStrength, reason: Variable shadows build in uniform: rainStrength ( = FunctionCall{clamp {[Id{rainStrength}, Number{0.0}, Number{1.0}]} })
java.lang.Exception: Variable shadows build in uniform: rainStrength
	at net.coderbot.iris.uniforms.custom.CustomUniforms.addVariable(CustomUniforms.java:175) ~[iris-mc1.19.3-1.5.1.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms.<init>(CustomUniforms.java:56) ~[iris-mc1.19.3-1.5.1.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:317) ~[iris-mc1.19.3-1.5.1.jar:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:329) ~[iris-mc1.19.3-1.5.1.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:217) ~[iris-mc1.19.3-1.5.1.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:664) ~[iris-mc1.19.3-1.5.1.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) ~[iris-mc1.19.3-1.5.1.jar:?]
	at net.coderbot.iris.Iris.onLoadingComplete(Iris.java:233) ~[iris-mc1.19.3-1.5.1.jar:?]
	at net.minecraft.class_442.handler$bgk000$iris$showSodiumIncompatScreen(class_442.java:564) ~[client-intermediary.jar:?]
	at net.minecraft.class_442.method_25426(class_442.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_41843(class_437.java:392) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:383) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1049) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:673) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:205) ~[1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]
[09:25:31] [Render thread/WARN]: [Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[09:25:31] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[09:25:32] [Render thread/INFO]: [STDOUT]: Baritone settings file not found, resetting.
[09:25:32] [Render thread/INFO]: Initializing Meteor Client
[09:25:32] [Render thread/INFO]: Rejects version: e8905d671a70eb83224f726c282b01b6451dad91
[09:25:32] [Render thread/INFO]: Rejects version: e8905d671a70eb83224f726c282b01b6451dad91
```

This crash only happens when I add Electron Mod. Minecraft opens showing a white window for a second then crashes.

**Comment by crosby-moe** [comment]
That is pretty funny

**Comment by phantomabid** [comment]
> That is pretty funny

Sorry but I don't understand your saying. What do you mean?

**Comment by Riminaru** [comment]
> Minecraft opens showing a white window for a second then crashes.

try removing loading optimization mixin
